apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - pvc.yaml
  - configmap.yaml
  - configmap-collector.yaml
  - secret.yaml
  - statefulset-mysql.yaml
  - deployment-backend.yaml
  - service-backend.yaml
  - deployment.yaml
  - deployment-analyzer.yaml
  - service.yaml
  - ingress.yaml
