package com.auctionboss.collect.source;

/**
 * 정규화된 경매 물건. TS {@code AuctionItemInput}과 필드 이름·의미가 같다. 없음은 {@code null}, 숫자는 전부 {@code Long},
 * 좌표·코드·날짜(YYYY-MM-DD)·시각 문자열은 {@code String}이다(design D9).
 */
public record SourceItem(
		String court,
		String caseNo,
		String itemNo,
		String address,
		String usageType,
		Long appraisalPrice,
		Long minBidPrice,
		String auctionDate,
		Long failedBidCount,
		String status,
		Long minArea,
		Long maxArea,
		String buildingDescription,
		Long minBidPriceRound1,
		Long minBidPriceRound2,
		Long minBidPriceRound3,
		Long minBidPriceRound4,
		Long minBidPriceRateRound1,
		Long minBidPriceRateRound2,
		String usageCodeLarge,
		String usageCodeMedium,
		String usageCodeSmall,
		String sido,
		String sigungu,
		String dong,
		String lotNumber,
		String buildingName,
		String buildingUnit,
		String coordinateX,
		String coordinateY,
		String coordinateLevel,
		String auctionTime,
		String auctionPlace,
		String auctionDecisionDate,
		Long auctionRound,
		String note,
		String duplicateCaseNo,
		String mergedCaseNo,
		String courtDepartment,
		String courtPhone,
		String statusCode,
		String itemStatusCode,
		String internalCaseNo,
		String courtCode) {
}
